# Generated by Django 4.2.15 on 2024-08-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("species", models.CharField(max_length=150)),
                ("notes", models.CharField(max_length=300)),
            ],
        ),
    ]
