# Generated by Django 4.2.15 on 2024-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0002_plant_attracts_plant_care_level_plant_growth_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
